import React from 'react'
import About from ".././components/about/About";
import Classes from ".././components/classes/Classes";
import Intro from ".././components/intro/Intro";
import Why from ".././components/why/Why";
import Features from ".././components/features/Features";
import Team from ".././components/team/Team";
import Testimonials from ".././components/testimonials/Testimonials";
import Blog from ".././components/blog/Blog";
import Partners from ".././components/partners/Partners";
import Footer from ".././components/footer/Footer";

function Home() {
    return (
        <div>
            <Intro
        flex="flex"
        jc="center"
        ai="center"
        padding="50px"
        border='4px solid black'
        background="linear-gradient(260deg,#1bb3eb 0%,#25efcb 100%)!important;"
        // bg="#25efcb 100%"
        bg="#fff"
        btnp="12px 36px"
        btnb="none"
        br="70px"
        fw="700"
        btnc="#25efcb"
        tc="#ffff"
        btn=""
        />
            <About
            flex="flex"
            jc="center"
            ai="center"
            aip="flex-start"
            jcp="flex-start"
            padding="50px"
            border='4px solid black'
            width="5%"
            heigt="5%"
            pp="relative"
            dp="absalout"
            top="20px"
            right="10px"
            dpadding="110px 170px"
            bg="#f0ecec"
            />
            <Classes
            flex="flex"
            jc="center"
            ai="center"
            aip="flex-start"
            jcp="flex-start"
            padding="20px 0"
            pi="20px"
            padding1="126px "
            border='4px solid black'
            flexdirection="column"
            borderb="4px solid red"
            flexd="row"
            background="#fafbfc"
            jcd="space-evenly"
            gap="25px"
            btnc="#25efcb"
            btnp="12px 36px"
            br="70px"
            btnb=" 1px solid #25efcb"
            position="absalout"
            positionl="relative"
            right="50%"
            left="50%"
            mt="25px"
            mb="25px"
            itbg="#fffff"
            />
            <Why
            flex="flex"
            jc="center"
            ai="center"
            padding="126px"
            border='4px solid black'
            background="linear-gradient(260deg,#1bb3eb 0%,#25efcb 100%)!important;"
            bg="#fbab7e "
            btnp="12px 36px"
            btnb="none"
            br="70px"
            fw="700"
            btnc="#25efcb"
            tc="#ffff"
            pc="black"
            margin="10px 0"/>
            <Features
            flex="flex"
            jc="center"
            ai="center"
            padding="124px"
            ta="center"
            bg2="#fafbfc"
            margin="70px 0"
            border="4px solid black"
            mh="auto"
            heigt="100%"
            width="100%"
            />
            <Team
            flex="flex"
            jc="center"
            ai="center"
            aip="flex-start"
            jcp="flex-start"
            padding="20px 0"
            pi="40px"
            padding1="126px "
            border='4px solid black'
            flexdirection="column"
            borderb="4px solid red"
            flexd="row"
            background="#fafbfc"
            jcd="space-evenly"
            gap="25px"
            btnc="#25efcb"
            btnp="12px 36px"
            br="70px"
            btnb=" 1px solid #25efcb"
            position="absalout"
            positionl="relative"
            right="50%"
            left="50%"
            mt="25px"
            mb="25px"
            itbg="#ffff"
            padding3="0"
            aligncontent="center"
            />
            <Testimonials
            flex="flex"
            jc="center"
            ai="center"
            aip="flex-start"
            jcp="flex-start"
            padding="20px 0"
            pi="20px"
            padding1="126px "
            border='4px solid black'
            flexdirection="column"
            flexdirectionr="row"
            borderb="4px solid red"
            flexd="row"
            background="#fafbfc"
            jcd="space-evenly"
            gap="25px"
            btnc="#25efcb"
            btnp="12px 36px"
            br="70px"
            btnb=" 1px solid #25efcb"
            position="absalout"
            positionl="relative"
            right="50%"
            left="50%"
            mt="25px"
            mb="25px"
            itbg="#ffff"
            padding3="0"
            aligncontent="center"
            bg="#25efcb 100%"

            />
            <Blog
            flex="flex"
            jc="center"
            ai="center"
            aip="flex-start"
            jcp="flex-start"
            padding="20px 0"
            pi="20px"
            padding1="126px "
            border='4px solid black'
            flexdirection="column"
            flexdirectionr="row"
            borderb="4px solid red"
            flexd="row"
            background="#fafbfc"
            jcd="space-evenly"
            gap="25px"
            btnc="#25efcb"
            btnp="12px 36px"
            br="70px"
            btnb=" 1px solid #25efcb"
            position="absalout"
            positionl="relative"
            right="50%"
            left="50%"
            mt="25px"
            mb="25px"
            itbg="#ffff"
            padding3="0"
            aligncontent="center"
            hcolor="#25efcb"
            backgroundcolor="#9b51e0"
            borderr="10px"
            textdecoration="none"
            mbb="50px"
            lightblue="#2ea3f2"
            mbbb="20px"
            width="100%"
            a="none"
            pbackground="50%"
            />
            <Partners
            hcolor="#25efcb"
            flex="flex"
            jc="center"
            ai="center"
            padding1="126px "
            gap="25px"
            />
            <Footer
            hcolor="#25efcb"
            flex="flex"
            jc="center"
            ai="center"
            padding1="126px "
            gap="25px"
            flexdirection="column"
            borderradius="70px"
            btnp="15px 15px"
            btnp2="20px 30px"
            btnc="#ffff"
            border="2px solid white"
            btnt="#25efcb"
            btnb="none"
            transperant="transparent"
            marginr="50px"
            margin="auto"
            />
        </div>
    )
}
export default Home